.\" Manpage for rpaste

.TH RPASTE "1" "June 2022" "rustypaste-cli 0.1.10" "User Commands"
.SH NAME
.PP
rpaste \- a CLI tool for rustypaste 

.SH SYNOPSIS
.PP
.B rpaste
[OPTIONS] <FILE(s)>

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
prints help information
.TP
\fB\-v\fR, \fB\-\-version\fR
prints version information
.TP
\fB\-o\fR, \fB\-\-oneshot\fR
generates one shot links
.TP
\fB\-p\fR, \fB\-\-pretty\fR
prettifies the output
.HP
\fB\-c\fR, \fB\-\-config\fR CONFIG sets the configuration file
.HP
\fB\-s\fR, \fB\-\-server\fR SERVER sets the address of the rustypaste server
.TP
\fB\-a\fR, \fB\-\-auth\fR TOKEN
sets the authentication token
.TP
\fB\-u\fR, \fB\-\-url\fR URL
sets the URL to shorten
.TP
\fB\-r\fR, \fB\-\-remote\fR URL
sets the remote URL for uploading
.TP
\fB\-e\fR, \fB\-\-expire\fR TIME
sets the expiration time for the link

.SH CONFIGURATION
A TOML file can be used to configure rpaste settings.
.TP
\fB[server]\fP
.RS
.IP \(bu 2
\fBaddress\fP: address of the rustypaste server
.IP \(bu 2
\fBauth_token\fP: authentication token
.RE
.TP
\fB[paste]\fP
.RS
.IP \(bu 2
\fBoneshot\fP: generate one shot links if set to true
.IP \(bu 2
\fBexpire\fP: expiration time for the links
.RE
.TP
\fB[style]\fP
.RS
.IP \(bu 2
\fBprettify\fP: prettify the output if set to true

.SH BUGS
Report bugs at <https://github.com/orhun/rustypaste-cli> or contact the author via email.

.SH ABOUT
.P
\f[I]rustypaste-cli\f[R] is maintained by Orhun Parmaksız <orhunparmaksiz@gmail.com>,
and released under the MIT license.
.PP
See the project homepage at <https://github.com/orhun/rustypaste-cli> for full documentation.

.SH SEE ALSO
.PP
<https://github.com/orhun/rustypaste>
